import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen overflow-hidden flex flex-col`}
      >
        <Header />

        <div className="flex flex-grow">
          <Sidebar />
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
