name: Next.js Bundle Size Analysis

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Analyze bundle size
        run: npx bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

      - name: Upload bundle stats
        uses: actions/upload-artifact@v2
        with:
          name: bundle-stats
          path: .next/stats.json
